/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  "aws_project_region": "ca-central-1",
  "aws_appsync_graphqlEndpoint": "https://wqixwwymj5cpvaiv7aastsxdwa.appsync-api.ca-central-1.amazonaws.com/graphql",
  "aws_appsync_region": "ca-central-1",
  "aws_appsync_authenticationType": "API_KEY",
  "aws_appsync_apiKey": "da2-2hokbx5mnfbt5fqzkhzaic63mm",
  "aws_cognito_region": "ca-central-1",
  "aws_user_pools_id": "ca-central-1_rRrfeOPOp",
  "aws_user_pools_web_client_id": "obkqcdueag7alats1of5fn8eo",
  "oauth": {},
  "aws_cognito_username_attributes": [
      "EMAIL"
  ],
  "aws_cognito_social_providers": [],
  "aws_cognito_signup_attributes": [
      "EMAIL"
  ],
  "aws_cognito_mfa_configuration": "OFF",
  "aws_cognito_mfa_types": [],
  "aws_cognito_password_protection_settings": {
      "passwordPolicyMinLength": 8,
      "passwordPolicyCharacters": [
          "REQUIRES_LOWERCASE",
          "REQUIRES_UPPERCASE",
          "REQUIRES_NUMBERS"
      ]
  },
  "aws_cognito_verification_mechanisms": [
      "EMAIL"
  ]
};


export default awsmobile;
